spring.application.name=BackendTFG

# --- CONEXION A BASE DE DATOS (Variables de Entorno) ---
# Aquí le decimos: "Busca una variable llamada DB_URL, si no existe, usa lo que está hardcodeado en Neon para local"
# Pero para evitar líos, lo dejaremos puramente con variables para Render.
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# --- JPA / HIBERNATE (Configurado para PostgreSQL) ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- JWT CONFIGURATION ---
application.security.jwt.secret-key=eW91clN0cm9uZ1NlY3JldEtleUZvclRGRzIwMjRCYXNlNjRFbmNvZGVkMjU2Qml0cw==
application.security.jwt.expiration=86400000

# --- HIKARI CP CONFIG (Optimizado para Nube) ---
spring.datasource.hikari.max-lifetime=180000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=2

# --- ARRASTRE DE ARCHIVOS ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB