spring.application.name=BackendTFG

# --- CONEXION DATABASE ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:validate}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- SECURITY JWT ---
application.security.jwt.secret-key=eW91clN0cm9uZ1NlY3JldEtleUZvclRGRzIwMjRCYXNlNjRFbmNvZGVkMjU2Qml0cw==
application.security.jwt.expiration=86400000

# --- HIKARI CP ---
spring.datasource.hikari.max-lifetime=180000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=2

# --- FILE UPLOAD ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# --- GMAIL CONFIG (SSL MODE - PUERTO 465) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=sergio.estudilloo7@gmail.com
spring.mail.password=khtbwtqgloxjbkgu
spring.mail.protocol=smtp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000