spring.application.name=BackendTFG

# --- CONEXIÓN A NEON DB ---
spring.datasource.url=jdbc:postgresql://ep-misty-poetry-ag61aa4w-pooler.c-2.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_X1zI4CBlKoDw&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_X1zI4CBlKoDw

# --- JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- JWT CONFIGURATION ---
# Clave fija y segura (Base64) para que no cambie al reiniciar el servidor
application.security.jwt.secret-key=eW91clN0cm9uZ1NlY3JldEtleUZvclRGRzIwMjRCYXNlNjRFbmNvZGVkMjU2Qml0cw==
# Tiempo de expiración: 86400000 ms = 24 horas
application.security.jwt.expiration=86400000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB