-- MySQL Script generated by MySQL Workbench
-- Mon Nov 10 19:47:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema club_futbol_tfg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema club_futbol_tfg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `club_futbol_tfg` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `club_futbol_tfg` ;

-- -----------------------------------------------------
-- Table `club_futbol_tfg`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_futbol_tfg`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `edad_min` INT NOT NULL,
  `edad_max` INT NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `club_futbol_tfg`.`liga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_futbol_tfg`.`liga` (
  `idliga` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `temporada` VARCHAR(15) NOT NULL,
  `nivel` VARCHAR(30) NULL DEFAULT NULL,
  `observaciones` VARCHAR(100) NULL DEFAULT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`idliga`),
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `liga_ibfk_1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `club_futbol_tfg`.`categoria` (`id_categoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `club_futbol_tfg`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_futbol_tfg`.`equipo` (
  `id_equipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `id_categoria` INT NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `observaciones` VARCHAR(255) NULL DEFAULT NULL,
  `id_liga` INT NOT NULL,
  PRIMARY KEY (`id_equipo`),
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  INDEX `fk_equipo_liga` (`id_liga` ASC) VISIBLE,
  CONSTRAINT `equipo_ibfk_1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `club_futbol_tfg`.`categoria` (`id_categoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_equipo_liga`
    FOREIGN KEY (`id_liga`)
    REFERENCES `club_futbol_tfg`.`liga` (`idliga`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `club_futbol_tfg`.`convocatoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_futbol_tfg`.`convocatoria` (
  `id_convocatoria` INT NOT NULL AUTO_INCREMENT,
  `id_equipo` INT NOT NULL,
  `fecha_evento` TIMESTAMP NULL DEFAULT NULL,
  `tipo` VARCHAR(30) NOT NULL,
  `observaciones` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_convocatoria`),
  INDEX `id_equipo` (`id_equipo` ASC) VISIBLE,
  CONSTRAINT `convocatoria_ibfk_1`
    FOREIGN KEY (`id_equipo`)
    REFERENCES `club_futbol_tfg`.`equipo` (`id_equipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `club_futbol_tfg`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_futbol_tfg`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(70) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  `fecha_alta` DATE NOT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `direccion` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `idx_usuario_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `club_futbol_tfg`.`jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_futbol_tfg`.`jugador` (
  `id_jugador` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `posicion` VARCHAR(30) NULL DEFAULT NULL,
  `dorsal` INT NULL DEFAULT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `telefono_contacto` VARCHAR(15) NULL DEFAULT NULL,
  `direccion` VARCHAR(120) NULL DEFAULT NULL,
  `fecha_alta` DATE NOT NULL,
  `fecha_baja` DATE NULL DEFAULT NULL,
  `observaciones` VARCHAR(255) NULL DEFAULT NULL,
  `equipo_principal` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_jugador`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `equipo_principal` (`equipo_principal` ASC) VISIBLE,
  CONSTRAINT `jugador_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `club_futbol_tfg`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `jugador_ibfk_2`
    FOREIGN KEY (`equipo_principal`)
    REFERENCES `club_futbol_tfg`.`equipo` (`id_equipo`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `club_futbol_tfg`.`convocatoria_jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_futbol_tfg`.`convocatoria_jugador` (
  `id_convocatoria` INT NOT NULL,
  `id_jugador` INT NOT NULL,
  PRIMARY KEY (`id_convocatoria`, `id_jugador`),
  INDEX `id_jugador` (`id_jugador` ASC) VISIBLE,
  CONSTRAINT `convocatoria_jugador_ibfk_1`
    FOREIGN KEY (`id_convocatoria`)
    REFERENCES `club_futbol_tfg`.`convocatoria` (`id_convocatoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `convocatoria_jugador_ibfk_2`
    FOREIGN KEY (`id_jugador`)
    REFERENCES `club_futbol_tfg`.`jugador` (`id_jugador`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `club_futbol_tfg`.`entrenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_futbol_tfg`.`entrenador` (
  `id_entrenador` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `especialidad` VARCHAR(50) NULL DEFAULT NULL,
  `licencia` VARCHAR(50) NULL DEFAULT NULL,
  `telefono_contacto` VARCHAR(15) NULL DEFAULT NULL,
  `fecha_alta` DATE NOT NULL,
  PRIMARY KEY (`id_entrenador`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `entrenador_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `club_futbol_tfg`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `club_futbol_tfg`.`equipo_entrenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_futbol_tfg`.`equipo_entrenador` (
  `id_equipo` INT NOT NULL,
  `id_entrenador` INT NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_equipo`, `id_entrenador`),
  INDEX `id_entrenador` (`id_entrenador` ASC) VISIBLE,
  CONSTRAINT `equipo_entrenador_ibfk_1`
    FOREIGN KEY (`id_equipo`)
    REFERENCES `club_futbol_tfg`.`equipo` (`id_equipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `equipo_entrenador_ibfk_2`
    FOREIGN KEY (`id_entrenador`)
    REFERENCES `club_futbol_tfg`.`entrenador` (`id_entrenador`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `club_futbol_tfg`.`incidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_futbol_tfg`.`incidencia` (
  `id_incidencia` INT NOT NULL AUTO_INCREMENT,
  `id_jugador` INT NULL DEFAULT NULL,
  `id_usuario` INT NOT NULL,
  `fecha_reporte` DATE NOT NULL,
  `tipo` VARCHAR(30) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_incidencia`),
  INDEX `id_jugador` (`id_jugador` ASC) VISIBLE,
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `incidencia_ibfk_1`
    FOREIGN KEY (`id_jugador`)
    REFERENCES `club_futbol_tfg`.`jugador` (`id_jugador`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `incidencia_ibfk_2`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `club_futbol_tfg`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `club_futbol_tfg`.`jugador_equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_futbol_tfg`.`jugador_equipo` (
  `id_jugador` INT NOT NULL,
  `id_equipo` INT NOT NULL,
  `observacion` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_jugador`, `id_equipo`),
  INDEX `id_equipo` (`id_equipo` ASC) VISIBLE,
  CONSTRAINT `jugador_equipo_ibfk_1`
    FOREIGN KEY (`id_jugador`)
    REFERENCES `club_futbol_tfg`.`jugador` (`id_jugador`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `jugador_equipo_ibfk_2`
    FOREIGN KEY (`id_equipo`)
    REFERENCES `club_futbol_tfg`.`equipo` (`id_equipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `club_futbol_tfg`.`solicitudinscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `club_futbol_tfg`.`solicitudinscripcion` (
  `id_solicitud` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_jugador` INT NULL DEFAULT NULL,
  `fecha_solicitud` DATE NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `motivo_rechazo` VARCHAR(255) NULL DEFAULT NULL,
  `observaciones` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_solicitud`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_jugador` (`id_jugador` ASC) VISIBLE,
  CONSTRAINT `solicitudinscripcion_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `club_futbol_tfg`.`usuario` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `solicitudinscripcion_ibfk_2`
    FOREIGN KEY (`id_jugador`)
    REFERENCES `club_futbol_tfg`.`jugador` (`id_jugador`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
